name: dart-dio-gen-test

packages:
  - packages/**

scripts:
  generate_all:
    run: |
      melos run pet_store &&
      melos run any_of_discriminator &&
      melos run any_of_no_discriminator &&
      melos run one_of_no_discriminator &&
      melos run one_of_discriminator &&
      melos run one_of_array_map_import &&
      melos run one_of_non_primitive &&
      melos run one_of_polymorphism_and_inheritance &&
      melos run one_of_primitive &&
      melos run ur_pet_store &&
      melos run ur_any_of_discriminator &&
      melos run ur_any_of_no_discriminator &&
      melos run ur_one_of_no_discriminator &&
      melos run ur_one_of_discriminator &&
      melos run ur_one_of_array_map_import &&
      melos run ur_one_of_non_primitive &&
      melos run ur_one_of_polymorphism_and_inheritance &&
      melos run ur_one_of_primitive

  pet_store:
    run: melos run generate_api
    env:
      SPEC: pet_store
    packageFilters:
      scope:
        - "pet_store"
  pet_store_bv:
    run: melos run generate_api
    env:
      SPEC: pet_store
    packageFilters:
      scope:
        - "pet_store_bv"
  any_of_no_discriminator:
    run: melos run generate_api
    env:
      SPEC: any_of_no_discriminator
    packageFilters:
      scope:
        - "any_of_no_discriminator"
  any_of_discriminator:
    run: melos run generate_api
    env:
      SPEC: any_of_discriminator
    packageFilters:
      scope:
        - "any_of_discriminator"
  one_of_no_discriminator:
    run: melos run generate_api
    env:
      SPEC: one_of_no_discriminator
    packageFilters:
      scope:
        - "one_of_no_discriminator"
  one_of_array_map_import:
    run: melos run generate_api
    env:
      SPEC: one_of_array_map_import
    packageFilters:
      scope:
        - "one_of_array_map_import"
  one_of_discriminator:
    run: melos run generate_api
    env:
      SPEC: one_of_discriminator
    packageFilters:
      scope:
        - "one_of_discriminator"
  one_of_non_primitive:
    run: melos run generate_api
    env:
      SPEC: one_of_non_primitive
    packageFilters:
      scope:
        - "one_of_non_primitive"
  one_of_polymorphism_and_inheritance:
    run: melos run generate_api
    env:
      SPEC: one_of_polymorphism_and_inheritance
    packageFilters:
      scope:
        - "one_of_polymorphism_and_inheritance"
  one_of_primitive:
    run: melos run generate_api
    env:
      SPEC: one_of_primitive
    packageFilters:
      scope:
        - "one_of_primitive"

  ur_pet_store:
    run: melos run ur_generate_api
    env:
      SPEC: pet_store
    packageFilters:
      scope:
        - "ur_pet_store"
  ur_any_of_discriminator:
    run: melos run ur_generate_api
    env:
      SPEC: any_of_discriminator
    packageFilters:
      scope:
        - "ur_any_of_discriminator"
  ur_any_of_no_discriminator:
    run: melos run ur_generate_api
    env:
      SPEC: any_of_discriminator
    packageFilters:
      scope:
        - "ur_any_of_no_discriminator"
  ur_one_of_array_map_import:
    run: melos run ur_generate_api
    env:
      SPEC: one_of_array_map_import
    packageFilters:
      scope:
        - "ur_one_of_array_map_import"
  ur_one_of_discriminator:
    run: melos run ur_generate_api
    env:
      SPEC: one_of_discriminator
    packageFilters:
      scope:
        - "ur_one_of_discriminator"
  ur_one_of_no_discriminator:
    run: melos run ur_generate_api
    env:
      SPEC: one_of_no_discriminator
    packageFilters:
      scope:
        - "ur_one_of_no_discriminator"
  ur_one_of_non_primitive:
    run: melos run ur_generate_api
    env:
      SPEC: one_of_non_primitive
    packageFilters:
      scope:
        - "ur_one_of_non_primitive"
  ur_one_of_polymorphism_and_inheritance:
    run: melos run ur_generate_api
    env:
      SPEC: one_of_polymorphism_and_inheritance
    packageFilters:
      scope:
        - "ur_one_of_polymorphism_and_inheritance"
  ur_one_of_primitive:
    run: melos run ur_generate_api
    env:
      SPEC: one_of_primitive
    packageFilters:
      scope:
        - "ur_one_of_primitive"
  generate_api:
    run: |
      melos exec -- java -jar ../openapi-generator-cli.jar generate \
      -i ../specs/$SPEC.yaml \
      -g dart-dio \
      -c generator_config.yaml &&
      melos exec -- rm -rf test &&
      melos run build_runner_delete
  ur_generate_api:
    run: |
      melos exec -- java -jar ../../openapi-generator-cli.jar generate \
      -i ../../specs/$SPEC.yaml \
      -g dart-dio \
      -c generator_config.yaml &&
      melos exec -- rm -rf test &&
      melos run build_runner_delete
  debug_generate_api:
    run: |
      melos exec -- java \
      -jar "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:6005" ../openapi-generator-cli.jar generate \
      -i ../specs/$SPEC.yaml \
      -g dart-dio \
      -c generator_config.yaml &&
      melos exec -- rm -rf test &&
      melos run build_runner_delete
  build_runner_delete:
    run: |
      melos exec -- flutter pub get &&
      melos exec -- dart run build_runner build -d &&
      melos exec -- dart fix --apply
      melos exec -- dart format .
