name: any_of_no_discriminator
version: 1.0.0
description: An
homepage: homepage

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  dio: '>=4.0.1 <5.0.0'
  freezed_annotation: '^2.0.3'
  json_annotation: '^4.4.0'

dev_dependencies:
  freezed: '^2.0.3'
  json_serializable: '^6.1.4'
  build_runner: any
  test: ^1.16.0
