name: any_of_no_discriminator
version: 1.0.0
description: An
homepage: homepage

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dio: '^5.0.0'
  freezed_annotation: '^2.2.0'
  json_annotation: '^4.8.0'

dev_dependencies:
  freezed: '^2.3.2'
  json_serializable: '^6.6.1'
  build_runner: any
  test: ^1.16.0
